# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'lookbook'

require 'fileutils'
require 'factory_girl'

require 'factories'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.formatter = :documentation

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  # FactoryGirl settings
  config.include FactoryGirl::Syntax::Methods

  # Create the lookbook object
  config.before(:all) do
    @db_path = File.expand_path('~/Library/Caches/lookbook_spec.db')
    @lookbook = Lookbook::Lookbook.new(@db_path)
    log_path = File.expand_path('~/Library/Caches/lookbook_spec.log')
    FileUtils.rm_f(log_path)
    log_file = File.open(log_path, 'w')
    $stdout = $stderr = log_file
  end

  config.after(:all) do
    FileUtils.rm_f(@db_path)
    $stdout = STDOUT
    $stderr = STDERR
  end
end
